### ISSUE TITLE
Create function or script that reads in nominal Showdown team sheet

### ISSUE THREAD

**Issue by TheSleepyShuckle** [TheSleepyShuckle/pyduck#6]
# Description
As a user, I eventually want to be able to look at the offensive moves that my team knows and see what types are covered by these moves.

As a developer, to begin with, I'd like make sure I can read in a Pokemon Showdown team file, since that will be a common text-based format.
# Test Plan
- Nominal case (one of my teams)

This issue will not cover off-nominal teams such as
- Not 6 Pokemon
- More than 6 Pokemon
- More or less than 4 moves on a given Pokemon
- etc
# Acceptance Criteria
Demonstrate that the function/script works by reading in a team file and correctly outputting:
- The length of the file
- The last line
- The lines with Pokemon listed on them
# Time Management
## Story Points
8
## Time Recording
2023-02-24 2245-2330 MST (0.75 hr)
2023-02-25 0930-1045 MST (1.25 hr)
## Total Time
2.0 hr

**Comment by Tikkitai** [comment]
Hi Sleepy Shuckle! 

Did you want assistance on this task?

Thanks, Tikkitai

**Comment by TheSleepyShuckle** [comment]
Hi Tikkitai,
I'm going to take this issue myself.  I'm not quite ready to make this project public, and I'm just using this particular issue to learn Python better.  But thanks for offering, and feel free to keep an eye on this project if it interests you 😊
-The Sleepy Shuckle

**Comment by TheSleepyShuckle** [comment]
Regarding branch updates, don't forget to:

- In GitHub, create a pull request for an issue's branch
- In GitHub, merge that pull request
- On local machine, switch branch to `main`
- On local machine, delete old branch:  `git branch -d <branch-name>`
- On local machine (while on `main`), `git pull`
